In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/2301_강남구_따릉이_이용정보.csv')
df

,대여일시,대여 대여소번호,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류
0,2023-01-01 00:11:12,2427,0,2023-01-01 00:18:25,2416.0,한티역 6번 출구,0,7,1196.26,1978.0,M,내국인
1,2023-01-01 00:14:25,2309,0,2023-01-01 00:18:43,2313.0,금원빌딩 앞,0,4,934.81,1963.0,NaN,내국인
2,2023-01-01 00:12:04,2431,0,2023-01-01 00:21:16,2404.0,대모산입구역 4번 출구 앞,0,9,1299.99,1989.0,NaN,내국인
3,2023-01-01 00:15:24,2333,0,2023-01-01 00:22:07,2327.0,뱅뱅사거리 랜드마크타워 앞,0,6,617.48,1960.0,NaN,내국인
4,2023-01-01 00:18:23,2423,0,2023-01-01 00:25:50,3651.0,개포동역 4번출구,0,7,1380.00,1995.0,NaN,내국인
...,...,...,...,...,...,...,...,...,...,...,...,...
34932,2023-01-31 23:49:48,4914,0,2023-02-01 00:13:19,2339.0,현대아파트 정문 앞,0,23,5270.93,1981.0,M,내국인
34933,2023-01-31 23:59:07,2342,0,2023-02-01 00:15:14,2324.0,천주교 대치 2동 교회 옆,0,16,1900.82,2004.0,M,내국인
34934,2023-01-31 23:33:46,2369,0,2023-02-01 00:28:07,2357.0,르네상스호텔사거리 역삼지하보도 3번출구 앞 (더 오번 빌딩 명동칼국수 앞),0,54,1890.91,1995.0,M,내국인
34935,2023-01-31 23:35:54,2304,0,2023-02-01 01:00:53,2371.0,한국우편사업진흥원,0,84,12660.00,2002.0,F,내국인
34936,2023-01-31 22:53:00,2306,0,2023-02-01 05:16:22,2301.0,현대고등학교 건너편,0,383,698.93,1953.0,M,내국인

In [18]:
df.대여일시 = pd.to_datetime(df.대여일시)

In [28]:
df[(df.대여일시.dt.hour == 17) | (df.대여일시.dt.hour == 18) | (df.대여일시.dt.hour == 19)].sort_values(ascending=True, by='대여일시')

,대여일시,대여 대여소번호,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류
496,2023-01-01 17:01:09,2341,99,2023-01-01 17:32:18,2341.0,일원역 4~5번 출구 사이,99,31,4710.00,1980.0,F,내국인
477,2023-01-01 17:01:45,2369,0,2023-01-01 17:08:57,2382.0,역삼동 sk뷰 501동앞,0,7,650.00,1978.0,NaN,내국인
473,2023-01-01 17:01:51,4917,0,2023-01-01 17:08:03,2342.0,대청역 1번출구 뒤,0,6,788.01,1996.0,M,내국인
495,2023-01-01 17:02:33,3614,0,2023-01-01 17:32:16,2340.0,삼호물산버스정류장(23370) 옆,0,29,4020.00,1983.0,NaN,내국인
564,2023-01-01 17:02:53,4908,0,2023-01-01 18:47:22,2429.0,압구정로데오역 6번출구,0,104,3580.00,1979.0,NaN,내국인
...,...,...,...,...,...,...,...,...,...,...,...,...
34667,2023-01-31 19:57:59,2331,0,2023-01-31 20:11:50,2421.0,신논현역 4번출구,0,13,2505.17,2002.0,NaN,내국인
34658,2023-01-31 19:58:00,2412,0,2023-01-31 20:03:16,3641.0,대청역,0,5,876.03,1999.0,NaN,내국인
34678,2023-01-31 19:58:04,2349,0,2023-01-31 20:18:10,2303.0,논현역 10번출구,0,20,1863.50,1988.0,NaN,내국인
34656,2023-01-31 19:58:26,2319,0,2023-01-31 20:01:53,4906.0,섬유센터 앞,0,3,500.00,1978.0,M,내국인
34666,2023-01-31 19:58:44,2377,0,2023-01-31 20:11:22,2411.0,세곡동 성당,0,12,2191.52,1993.0,M,내국인

In [39]:
dfs = []

for num in ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']:
    df = pd.read_csv(f'../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/23{num}_강남구_따릉이_이용정보.csv')
    df.대여일시 = pd.to_datetime(df.대여일시)
    dfs.append(df[(df.대여일시.dt.hour == 17) | (df.대여일시.dt.hour == 18) | (df.대여일시.dt.hour == 19)].sort_values(ascending=True, by='대여일시').반납대여소번호)

In [51]:
dfs = [i.astype(int) for i in dfs]

In [59]:
df1_2023 = dfs[0]
df2_2023 = dfs[1]
df3_2023 = dfs[2]
df4_2023 = dfs[3]
df5_2023 = dfs[4]
df6_2023 = dfs[5]
df7_2023 = dfs[6]
df8_2023 = dfs[7]
df9_2023 = dfs[8]
df10_2023 = dfs[9]
df11_2023 = dfs[10]
df12_2023 = dfs[11]

In [61]:
df1_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df1_2023.csv')
df2_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df2_2023.csv')
df3_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df3_2023.csv')
df4_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df4_2023.csv')
df5_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df5_2023.csv')
df6_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df6_2023.csv')
df7_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df7_2023.csv')
df8_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df8_2023.csv')
df9_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df9_2023.csv')
df10_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df10_2023.csv')
df11_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df11_2023.csv')
df12_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df12_2023.csv')