In [12]:
import pandas as pd
df = pd.read_csv("../3조 공유폴더/2023 강남구 따릉이 이용정보/2301_강남구_따릉이_이용정보.csv")
df.head()

,대여일시,대여 대여소번호,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류
0,2023-01-01 00:11:12,2427,0,2023-01-01 00:18:25,2416.0,한티역 6번 출구,0,7,1196.26,1978.0,M,내국인
1,2023-01-01 00:14:25,2309,0,2023-01-01 00:18:43,2313.0,금원빌딩 앞,0,4,934.81,1963.0,NaN,내국인
2,2023-01-01 00:12:04,2431,0,2023-01-01 00:21:16,2404.0,대모산입구역 4번 출구 앞,0,9,1299.99,1989.0,NaN,내국인
3,2023-01-01 00:15:24,2333,0,2023-01-01 00:22:07,2327.0,뱅뱅사거리 랜드마크타워 앞,0,6,617.48,1960.0,NaN,내국인
4,2023-01-01 00:18:23,2423,0,2023-01-01 00:25:50,3651.0,개포동역 4번출구,0,7,1380.00,1995.0,NaN,내국인

In [22]:
import pandas as pd
from datetime import time

df = pd.read_csv("../3조 공유폴더/2023 강남구 따릉이 이용정보/2301_강남구_따릉이_이용정보.csv")

df["반납일시"] = pd.to_datetime(df["반납일시"])

filtered = df[
    (df["반납일시"].dt.time >= time(7, 0, 0)) &
    (df["반납일시"].dt.time <= time(10, 0, 0))
]
filtered.head()

,대여일시,대여 대여소번호,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류
119,2023-01-01 06:58:35,2325,99,2023-01-01 07:00:15,2325.0,대치삼성아파트 앞 교차로,99,1,0.00,1991.0,NaN,내국인
120,2023-01-01 06:49:27,2348,0,2023-01-01 07:00:56,2405.0,청담공원앞 교차로,0,11,1415.43,1995.0,M,내국인
121,2023-01-01 06:32:11,2306,0,2023-01-01 07:02:59,2314.0,청담나들목입구,0,30,3659.65,NaN,NaN,비회원
122,2023-01-01 07:01:04,2302,0,2023-01-01 07:05:47,2303.0,논현역 10번출구,0,4,670.00,2004.0,M,내국인
123,2023-01-01 07:10:10,2334,0,2023-01-01 07:16:51,2382.0,역삼동 sk뷰 501동앞,0,6,1280.15,1996.0,M,내국인